# Generated by Django 5.0.1 on 2024-02-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_task_due_date_alter_task_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="comments",
            field=models.TextField(null=True),
        ),
    ]
