# Generated by Django 5.0.1 on 2024-02-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_task_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="comments",
            new_name="notes",
        ),
    ]
